/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package events;

import java.awt.Dimension;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import matricproject.DataHandler;
import matricproject.Event;
import menu.MenuItem;

/**
 *
 * @author User
 */
public class EventItem extends javax.swing.JPanel {

    /**
     * @return the event
     */
    public ArrayList<EventItem> getEvent() {
        return event;
    }
public boolean isShowing() {
        return showing;
    }
    /**
     * indicates is the menu is currently showing or not
     */
    public void setShowing(boolean showing) {
        this.showing = showing;
    }

    /**
     * @return the event
     */
    
    /**
     * Creates new form EventItem
     */
    
     private final ArrayList<EventItem> event = new ArrayList<>();
      private ActionListener act;
      
       public EventItem(String e,String u,  EventItem... event  ) {
        initComponents();
        lblTeams.setText(e);
        lblDate.setText(u);
        
       
         this.setSize(new Dimension(Integer.MAX_VALUE, 85));
        this.setMaximumSize(new Dimension(Integer.MAX_VALUE, 85));
        this.setMinimumSize(new Dimension(Integer.MAX_VALUE, 85));
        
        for (int i = 0; i < event.length; i++) {
            this.event.add(event[i]);
        }
    }
//      public EventItem(String e,String u,  EventItem... event  ) {
//        initComponents();
//        lblTeams.setText(e);
//        lblDate.setText(u);
//        
//        
//        
//        
//         this.setSize(new Dimension(Integer.MAX_VALUE, 85));
//        this.setMaximumSize(new Dimension(Integer.MAX_VALUE, 85));
//        this.setMinimumSize(new Dimension(Integer.MAX_VALUE, 85));
//        
//         for (int i = 0; i < event.length; i++) {
//            this.event.add(event[i]);
//            event[i].setVisible(true);
//
//        }
//        
//    }
//    public EventItem(Event e, ActionListener act, EventItem... event ) {
//        initComponents();
//        lblTeams.setText(e.getTeamA() + "vs" + e.getTeamB());
//        lblDate.setText(""+e.getDate());
//        
//         DataHandler dh = new DataHandler();
//        lblTeamA.setText(e.getTeamA());
//        lblTeamB.setText(e.getTeamB());
//        
//        lblOddsA.setText(""+dh.calculatingOddsA(e));
//        lblOddsB.setText(""+dh.calculatingOddsB(e));
//        
//         if (act != null) {
//            this.act = act;
//        }
//        
//         this.setSize(new Dimension(Integer.MAX_VALUE, 85));
//        this.setMaximumSize(new Dimension(Integer.MAX_VALUE, 85));
//        this.setMinimumSize(new Dimension(Integer.MAX_VALUE, 85));
//        
//         for (int i = 0; i < event.length; i++) {
//            this.event.add(event[i]);
//            event[i].setVisible(false);
//
//        }
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTeamA = new javax.swing.JLabel();
        lblOddsA = new javax.swing.JLabel();
        lblTeams = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblTeamB = new javax.swing.JLabel();
        lblOddsB = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setPreferredSize(new java.awt.Dimension(925, 85));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        lblTeamA.setText("TeamA");

        lblOddsA.setText("Odds A");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblTeamA, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(lblOddsA, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTeamA, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblOddsA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblTeams.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTeams.setText("TeamA vs TeamB");

        lblDate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDate.setText("date and time of game");

        lblTeamB.setText("TeamB");

        lblOddsB.setText("Odds B");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblTeamB, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(lblOddsB, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTeamB, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblOddsB, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTeams, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(217, Short.MAX_VALUE))
            .addComponent(jSeparator1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblTeams)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents
private boolean showing = false;
    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
         if (showing) {
            hideMenu();
            showing = false;
        } else {
            showMenu();
            showing = true;
        }
    }//GEN-LAST:event_formMousePressed

 private void showMenu() {
        new Thread(new Runnable() {
            @Override
            public void run() {
                for (int i = 0; i < event.size(); i++) {
                    sleep();
                    event.get(i).setVisible(true);
                }
//                showing = true;
//                getParent().repaint();
//                getParent().revalidate();
            }
        }).start();
    }

 private void hideMenu() {
        new Thread(new Runnable() {
            @Override
            public void run() {
                for (int i = 0; i < event.size(); i++) {
                    sleep();
                    event.get(i).setVisible(true);
                }
//                showing = true;
//                getParent().repaint();
//                getParent().revalidate();
            }
        }).start();
    }
private void sleep() {
        try {
            Thread.sleep(20);
        } catch (Exception e) {
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblOddsA;
    private javax.swing.JLabel lblOddsB;
    private javax.swing.JLabel lblTeamA;
    private javax.swing.JLabel lblTeamB;
    private javax.swing.JLabel lblTeams;
    // End of variables declaration//GEN-END:variables
}
